docs(scf): yaml 格式说明
RayWangQvQ/BiliBiliToolPro pull request #23
Opened 2022-03-02 15:09 UTC by catlair

【内容】：
请描述您将贡献的内容

2022-03-04 06:30 UTC, RayWangQvQ approved these changes

2022-03-04 06:32 UTC, RayWangQvQ requested changes
感谢补充！
请修改PR到我的develop分支，我会合并到下一版本中。

2022-03-04 12:02 UTC, catlair commented
> 感谢补充！ 请修改PR到我的develop分支，我会合并到下一版本中。

sls 有个 bug，exitcode 为 0. 官方说是修复了，但实际上还存在。

2022-03-05 13:30 UTC, merged

2022-03-05 13:36 UTC, RayWangQvQ commented
很久没用云函数了，不太了解。exitcode 为 0 是指运行时会偶发中止是吗

2022-03-06 06:07 UTC, catlair commented
> 很久没用云函数了，不太了解。exitcode 为 0 是指运行时会偶发中止是吗

不管sls是否运行成功，sls 的 exitcode 始终为 0，导致action 看起来是部署成功了。issues 中有几个都是说自己部署成功了，但是腾讯云的控制台没有。其实就是这个bug造成了。