Develop
RayWangQvQ/BiliBiliToolPro pull request #256
Opened 2022-08-22 11:27 UTC by syrinka

【内容】：
请描述您将贡献的内容

- **fix:** cron 加载环境变量未对特殊字符进行转义
- **feat:** 环境变量 `Ray_Crontab`，替代 `my_crontab` 文件的功能，已补充对应文档

2022-08-22 16:00 UTC, RayWangQvQ requested changes

2022-08-22 16:00 UTC, RayWangQvQ commented on docker/entry.sh
> +elif [ -e "/app/custon_crontab" ]; then
Please confirm whether it should be `/app/custom_crontab`

2022-08-22 16:06 UTC, syrinka commented on docker/entry.sh
> +elif [ -e "/app/custon_crontab" ]; then
大意了😣已fix

2022-08-22 16:30 UTC, RayWangQvQ approved these changes

2022-08-22 19:04 UTC, syrinka commented
> 请教个问题，之前的环境变量是写到`/etc/environment`里，现在改成cron文件里主动"BASH_ENV=/etc/cron.env"，这样改是有什么原因吗？

原来的写法无法正确处理一些字符，比如 `#` 和换行符等，解析到的环境变量可能与实际传入的不一致

ref:
- https://stackoverflow.com/a/48651061 现在用的方法
- https://serverfault.com/a/723116 `/etc/environment` 的行为

2022-08-23 02:52 UTC, merged

2022-08-23 02:55 UTC, RayWangQvQ commented
Merged, these update will be included in the next release version, thx for your nice work!