docker: Fix and optimize
RayWangQvQ/BiliBiliToolPro pull request #414
Opened 2023-02-02 10:47 UTC by zclkkk

【内容】：
* 移除了compose配置文件中不必要的配置。它们应该在appsetting中被设置。
* 移除了文档中对Docker命令的支持
* 将appsetting.json与上游同步
* 修复了启动脚本中的typo
* 补全corntab的默认设定

2023-02-07 05:11 UTC, RayWangQvQ requested changes

2023-02-07 05:11 UTC, RayWangQvQ commented on docker/README.md
> -## 3. 方式二：Docker指令
建议保留docker cmd，因为很多托管平台（such as 宝塔、一些路由系统）不能使用docker compose

2023-02-07 05:17 UTC, RayWangQvQ requested changes

2023-02-07 05:17 UTC, RayWangQvQ commented on docker/README.md
> -wget https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/src/Ray.BiliBiliTool.Console/appsettings.json
建议保留使用项目中的配置，避免维护多个文件，sample里的后续会删除，并考虑提供一键安装的shell脚本

2023-02-07 11:10 UTC, zclkkk commented on docker/README.md
> -## 3. 方式二：Docker指令
好的，晚点修改

2023-02-07 11:11 UTC, zclkkk commented on docker/README.md
> -wget https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/src/Ray.BiliBiliTool.Console/appsettings.json
但是appsettings.json里面的Cron设置并不会在Docker下生效

2023-02-07 11:12 UTC, zclkkk commented on docker/README.md
> -wget https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/src/Ray.BiliBiliTool.Console/appsettings.json
或者是我操作有问题？

2023-02-09 15:29 UTC, RayWangQvQ commented on docker/README.md
> -wget https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/src/Ray.BiliBiliTool.Console/appsettings.json
嗯不会生效的，之前准备写成docker下跑起来用quartz定时触发，目前还没改，所以是没用的

2023-02-10 18:55 UTC, closed without merging