优化部分代码规范
RayWangQvQ/BiliBiliToolPro pull request #530
Opened 2023-05-06 08:18 UTC by hjkl950217

【内容】：
fork后部署到railay，用docker的方式跑。发现添加环境变量后也没有切换到login任务上，就看了一眼代码想追追。
结果没有追出来，不过顺手优化了部分代码，未修改过逻辑，让代码更好阅读一点（顺便混个贡献者233）

2023-05-24 05:38 UTC, RayWangQvQ requested changes

2023-05-24 05:38 UTC, RayWangQvQ commented on docs/runInLocal.md
> +下载解压后，进入应用目录，执行`.\Ray.BiliBiliTool.Console.exe --runTasks=Login`
这儿不行的，只有win可以直接运行exe，linux系需要使用dotnet cli来运行

2023-05-24 05:40 UTC, hjkl950217 commented on docs/runInLocal.md
> +下载解压后，进入应用目录，执行`.\Ray.BiliBiliTool.Console.exe --runTasks=Login`
现在不需要了。 因为net6起可以直接编译为一个文件，独立部署的。  所以像这样直接运行就行了

2023-05-24 05:41 UTC, hjkl950217 commented on docs/runInLocal.md
> +下载解压后，进入应用目录，执行`.\Ray.BiliBiliTool.Console.exe --runTasks=Login`
或者完善一下？ 如果还是编译为dll，那么需要`dotnet cli`来运行， 如果是独立部署的则不需要了

2023-05-24 06:13 UTC, RayWangQvQ requested changes

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/Constants.cs
> +            Dictionary<string, string> dic = new Dictionary<string, string>()
建议保留var吧。

目前这边采用的对var和new()的规范是2个：

1、同一条语句如果=号两边有重复，建议使用var或new()来简化

如这里的`Dictionary<string, string> dic = new Dictionary<string, string>()`，建议简化为`var dic = new Dictionary<string, string>()`或者`Dictionary<string, string> dic = new ()`

2、对于函数调用的返回值，如果函数名能直观看返回值，可以var，如果不能，建议用类。

比如`var re= _biliApi.GetUserInfo(int id)`，这里var就要看上下文了，如果上下文复杂，且dto也复杂，建议使用原类代替var。

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/Constants.cs
> +            Dictionary<string, string> dic = new Dictionary<string, string>()
建议保留var，理由同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/EnvironmentVariablesExcludeEmptyConfigurationProvider.cs
> +    /// 自定义的排除空值的环境变量提供者<para></para>
建议删除

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/EnvironmentVariablesExcludeEmptyConfigurationProvider.cs
> +            if(_removeKeyPrefix)
if只包含一条语句且较短，建议不换行

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/EnvironmentVariablesExcludeEmptyConfigurationSource.cs
> +    /// 自定义的排除空值的环境变量配置源<para></para>
意义不明

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/Options/DailyTaskOptions.cs
> +                if(string.IsNullOrWhiteSpace(SupportUpIds) | SupportUpIds == "-1")
建议保留if和(的空格，以vs格式化标准为准，vs的格式化Ctrl+K+F，会保留空格

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/Options/DailyTaskOptions.cs
> +                foreach(string item in array)
空格，同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/Options/DailyTaskOptions.cs
> +                    if(long.TryParse(item.Trim(), out long upId))
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +                if(!pass)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +                if(tasks.Contains("Login"))
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +                    for(int i = 0 ; i < _cookieStrFactory.Count ; i++)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +                            if(isNotifySingle)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +                if(!isNotifySingle)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +            if(_securityOptions.IsSkipDailyTask)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +            if(_configuration["RunTasks"].Contains("Login") || _configuration["RunTasks"].Contains("Test"))
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +            if(_securityOptions.RandomSleepMaxMin > 0)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +            foreach(string task in tasks)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/Program.cs
> +            catch(Exception ex)
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/Program.cs
> +                if(args is { Length: > 0 })
同上

2023-05-24 06:13 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Console/Program.cs
> +                if(args != null && args.Length > 0)
同上

2023-05-24 06:15 UTC, RayWangQvQ commented
ths for your PR，please check the review comments, and we can talk about it freely here~

2023-05-27 05:16 UTC, RayWangQvQ commented on docs/runInLocal.md
> +下载解压后，进入应用目录，执行`.\Ray.BiliBiliTool.Console.exe --runTasks=Login`
单文件发布生成的的linux的可执行文件，不是exe，在下面`3. Linux`里，exe应该只有win系可以运行

2023-06-06 02:31 UTC, hjkl950217 commented on src/Ray.BiliBiliTool.Config/EnvironmentVariablesExcludeEmptyConfigurationSource.cs
> +    /// 自定义的排除空值的环境变量配置源<para></para>
这个是summary里面用于换行的，在提示时可以看到换行了

2023-06-06 02:33 UTC, hjkl950217 commented on src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs
> +            foreach(string task in tasks)
这行和其他地方不一样的，Scope同类的有许多，写明的时知道代码使用的是那一个接口下面的。

2023-06-06 03:07 UTC, hjkl950217 commented
这下应该差不多了，转化为了PR改了一下设置。。PR完又改回去了（狗头）

2023-06-11 14:19 UTC, RayWangQvQ approved these changes

2023-06-11 14:20 UTC, merged